language: java

before_script:
# should be empty
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx1g"
 
jdk:
# Runs in an endless loop for SecureRandom:(
#  - openjdk6
#  - oraclejdk7
  - oraclejdk8
  
cache:
  directories:
  - $HOME/.m2
  